# Use Node.js 14 LTS as the base image
FROM node:14

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose port PORT
ENV PORT 3030

EXPOSE $PORT

# Start the Express server
CMD ["node", "server.js"]
